### ISSUE TITLE
first blood..

### ISSUE THREAD

**Issue by jamninetyfive** [Hector-Chong/native-wechat#1]
first blood..

great work. it seems to support newArch?

hope you save RN 3rd libs future(especially CN)

**Comment by Hector-Chong** [comment]
Yes, Native WeChat does support newArch with TurboModule.
Supporting kinds of third libs is gonna be a huge job and exhausting. This lib is built from my work and WeChat OpenSDK is probably the most used within an app in China. Is there any other most used lib to be supported for RN?

**Comment by jamninetyfive** [comment]
App is CN. usually use bugly, jpush, umeng, video player(like flutter ijkplayer), toutiao ad sdk, all need turbo module.

**Comment by jamninetyfive** [comment]
also look forward to your vant ui for rn. ui lib is less...

**Comment by Hector-Chong** [comment]
Libs for collecting performance data like Umeng and Bugly (why not Sentry?) should be initialized asap, which means TurboModule is not necessary here. Most of the rest have their own RN libs but without TurboModule and they are supposed be maintained by their owners because it is their job and I cannot guarantee the APIs would be changed or not.

**Comment by Hector-Chong** [comment]
> also look forward to your vant ui for rn. ui lib is less...

Thanks for asking. I'm kinda busy building a bundle management system for RN recently. So, this project will be put off for some while.

**Comment by jamninetyfive** [comment]
> management

bundle management system of rn,  like code-push ? it will support splite bundle? this sounds good. hope open-source.

**Comment by Hector-Chong** [comment]
> > management
> 
> bundle management system of rn, like code-push ? it will support splite bundle? this sounds good. hope open-source.

It's similar to CodePush in some way. But it does not support features like signing or testing which should be processed by Jenkins Pipeline. Of course, it supports code-splitting. It separates the code into three parts: basic, business, and dynamic. 
 Only the last two parts will be bundled and delivered for each version.

However, when it comes to a major change, let's say you imported Reanimated into your project, you still have to re-submit your app to the App Store because the native code has changed.

**Comment by jamninetyfive** [comment]
Yes, I am clear about how it work. only worked under the change of js code. I am using own deploy code push now. I look forward to your work.

**Comment by jamninetyfive** [comment]
I have recently encountered a demand for maps. It seems that there is currently no map library that supports new purchases. Are you interested.

**Comment by Hector-Chong** [comment]
> I have recently encountered a demand for maps. It seems that there is currently no map library that supports new purchases. Are you interested.

What kind of map? Google map, AMap or ...?

**Comment by jamninetyfive** [comment]
baidu map or gaode map

**Comment by Hector-Chong** [comment]
Well, Amap (or Gaode) is more promising when it comes to something global, I suppose.

In any case, I can't wait to hear more details from you.

By the way, I have not set up any notifications of GitHub, it would be lovely if you send the preliminary plan or instruction about the project to my personal email: i@hector.im. This way, I can get your information more quickly.
