### ISSUE TITLE
isWechatInstalled 返回值是undefined

### ISSUE THREAD

**Issue by meiqi1992** [Hector-Chong/native-wechat#12]
let wechatIsInstal =  await isWechatInstalled()

我打印wechatIsInstal 结果是undefined，但是我看原生代码这里是yes
<img width="801" alt="image" src="https://user-images.githubusercontent.com/15257730/206352782-f54f6c37-082c-4117-9450-32333986cc19.png">

**Comment by Hector-Chong** [comment]
`isWechatInstalled` 返回的是一个 Pending 状态的 Promise。

当 Promise 被 Resolved 时，意味着微信已安装，否则未安装并且你应该在这里使用 `try...catch` 包裹 `await`。

`isWechatInstalled` returns a pending promise.

When the promise is resolved, it means WeChat is installed on your device. Otherwise, it doesn't and you should wrap the `await` with `try...catch` here.

**Comment by Hector-Chong** [comment]
没有问题，我会在下一个版本为这个功能提供支持。

No problem. This feature will be delivered in the next version.

**Comment by meiqi1992** [comment]
> 

赞👍

**Comment by meiqi1992** [comment]
android 碰到的问题
1、isWechatInstalled 不管手机有没有装微信都是走到catch
    try {
            await isWechatInstalled()
        } catch (error) {
            //未安装微信
        }
2、分享图片有的会比较大，拉不起微信，分享不成功
3、微信支付，拉不起微信，ios上支付没问题
    try {
                await requestPayment({})
                console.log('走不到这里')
         } catch (error) {
                console.log('也不走到这里')
        }

**Comment by Hector-Chong** [comment]
感谢你的反馈，我会尽快处理。

Thank you for your feedback. The above will be fixed asap.

**Comment by jsonchou** [comment]
https://github.com/Hector-Chong/native-wechat/blob/main/src/hooks.ts

try catch
await
then

任何方式，都是undefined。

请勿关闭该issure。
